#######################################################################################################################
# File Name  : Makefile.config                                                                                        #
# Description: This makefile contains the target specific project settings (will be included by Makefile)             #
# Project    : Vector Basic Runtime System                                                                            #
# Module     : BrsHw for platform ARMcommon                                                                           #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# COPYRIGHT                                                                                                           #
#---------------------------------------------------------------------------------------------------------------------#
# Copyright (c) 2018 by Vector Informatik GmbH.                                                  All rights reserved. #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# AUTHOR IDENTITY                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# Name                          Initials      Company                                                                 #
# ----------------------------  ------------  ------------------------------------------------------------------------#
# Philipp Duller                vispd         Vector Informatik GmbH                                                  #
# Jens Haerer                   visjhr        Vector Informatik GmbH                                                  #
# Carlos Sanchez                viscs         Vector Informatik GmbH                                                  #
# Benjamin Walter               visbwa        Vector Informatik GmbH                                                  #
# Sascha Mauser                 vismaa        Vector Informatik GmbH                                                  #
#---------------------------------------------------------------------------------------------------------------------#
# REVISION HISTORY                                                                                                    #
#---------------------------------------------------------------------------------------------------------------------#
# Version   Date        Author  Description                                                                           #
# --------  ----------  ------  --------------------------------------------------------------------------------------#
# 01.00.00  2013-11-14  vispdr  Initial version for ARM_BRS                                                           #
# 01.00.01  2014-03-07  visjhr  Added support for Xilinx Zynq7000 platform (VEBN01032)                                #
# 01.00.02  2014-03-26  viscsz  Added support for Freescale iMX6X platform (VEBN01013)                                #
# 01.00.03  2014-08-20  visbwa  Added OS_USECASE for new Brs structure                                                #
# 02.00.00  2014-08-22  visbwa  Splitted Makefile.config into ArmCommon + Platform specific file                      #
# 02.00.01  2015-07-09  visbwa  Review                                                                                #
# 02.01.00  2016-06-16  visbwa  Adapted complete file header structure for zBrs_Template@root[2.00.01]                #
# 02.01.01  2017-02-10  vismaa  Added OS_USECASE = OSGEN7                                                             #
# 02.01.02  2017-06-09  visbwa  Added ARM_COMP_VERSION for ARM compiler separation                                    #
# 02.01.03  2017-11-03  visbwa  Added IAR_COMP_VERSION for IAR compiler separation                                    #
# 02.01.04  2018-02-15  vismaa  Added floating point support (ARM_FPU_USED) for GreenHills                            #
# 02.01.05  2018-03-14  vismaa  Removed ARM_COMP_VERSION, now separated into two different Makefiles                  #
# 02.01.06  2018-06-13  vismaa  Deleted OS_USECASE OS and SAFECTX                                                     #
#######################################################################################################################

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select clock frequency of main oscillator (MHz)
#------------------------------------------------------------------------------
MAIN_OSC_CLK = 8

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select BRS time base clock (MHz). PLL will be used to create this frequency.
# Possible values are:  Derivative specific
#------------------------------------------------------------------------------
TIMEBASE_CLOCK = 96

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Specify the size of the Stack (in Byte & Hexadecimal)
#   (a default value for Cortex-A should be 0x1400)
#------------------------------------------------------------------------------
STACKSIZE = 0x30000

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Choose CPU-Instruction-Set. Possible values are: ARM THUMB
# Hint: - Thumb-code needs ~ 30-40% less space, but works around 30% slower.
#       - Till ARM_Achitecture_v4 Thumb-Mode is supported.
#       - Cortex M-Series ONLY supports Thumb-Code
#------------------------------------------------------------------------------
INSTRUCTION_SET = ARM

#------------- Can be filled out for GNU and GreenHills compiler --------------
# Configure here, if the Floating Point Unit should be used (compiler options).
# Possible values are: 0 - Disabled (Default)
#                      1 - Enabled
#------------------------------------------------------------------------------
ARM_FPU_USED = 

#------------------------- Can be filled out ----------------------------------
# Select the type of used OS.
# Possible values are: BRS      Timer/IRQ generated by BRS (Default)
#                      OSGEN7   Os_CoreGen7 based MICROSAR OS
#------------------------------------------------------------------------------
OS_USECASE = OSGEN7

#------------------------- Can be filled out ----------------------------------
# User defined linker command file
# If left empty, the linker command file will be 
# generated by the Makesupport as $(PROJECT_NAME).$(LNK_SUFFIX)
# User Linker Script Support is currently only implemented for Greenhills!
#------------------------------------------------------------------------------
USER_LINKER_COMMAND_FILE = 

#------------------------ Must be filled out for IAR compiler -----------------
# Select the version of IAR compiler to be used.
# Hint: Just some dependency defines for usage of intrinsics.h are different
# Possible values are: 7  -  Embedded Workbench version 7.xx
#                      8  -  Embedded Workbench version 8.xx
#------------------------------------------------------------------------------
IAR_COMP_VERSION = 

#------------------------------------------------------------------------------
# All platform specific parameters are set within a Platform-file.
# Values, that are fix for the specific platform, are hard-coded within there
#------------------------------------------------------------------------------
include Makefile.Platform.config
